# Generated by Django 5.2 on 2025-04-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
