# Generated by Django 5.2 on 2025-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspot', '0002_blog_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
