# Generated by Django 5.2 on 2025-04-18 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogspot', '0004_forumpost_forumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogspot.forumpost'),
        ),
    ]
